services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: internship_ats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://postgres:12345@db:5432/internship_ats
      CORS_ORIGINS: http://localhost:80,http://localhost:5173
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - uploads:/app/uploads
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
  uploads:
