FROM evoapicloud/evolution-api:v2.3.7
WORKDIR /evolution
RUN chmod +x ./Docker/scripts/* 2>/dev/null || true
ENTRYPOINT ["/bin/bash", "-c", ". ./Docker/scripts/deploy_database.sh 2>&1 && npm run start:prod"]
