"""drop unique email mobile

Revision ID: 1e98d3f2331f
Revises: 
Create Date: 2026-07-22 20:13:12.919648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e98d3f2331f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if any(
        constraint.get("name") == "applications_mobile_key"
        for constraint in inspector.get_unique_constraints("applications")
    ):
        op.drop_constraint("applications_mobile_key", "applications", type_="unique")

    if any(index.get("name") == "ix_applications_email" for index in inspector.get_indexes("applications")):
        op.drop_index("ix_applications_email", table_name="applications")

    if not any(index.get("name") == "ix_applications_email" for index in sa.inspect(bind).get_indexes("applications")):
        op.create_index("ix_applications_email", "applications", ["email"], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_email'), table_name='applications')
    op.create_index('ix_applications_email', 'applications', ['email'], unique=True)
    op.create_unique_constraint('applications_mobile_key', 'applications', ['mobile'])
    # ### end Alembic commands ###
