"""add_remarks_to_interviews

Revision ID: 2f8ced6505b3
Revises: 1e98d3f2331f
Create Date: 2026-07-22 20:59:02.611991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f8ced6505b3'
down_revision: Union[str, None] = '1e98d3f2331f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    columns = {column["name"] for column in sa.inspect(op.get_bind()).get_columns("interviews")}
    if "remarks" not in columns:
        op.add_column("interviews", sa.Column("remarks", sa.Text(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'remarks')
    # ### end Alembic commands ###
